# Generated by Django 4.1.7 on 2023-03-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0003_aluno_votos'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='votosmax',
            field=models.IntegerField(default=0),
        ),
    ]
